name: PR with translations
on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}

# permissions:
#   id-token: write
#   contents: read
#   pull-requests: write

jobs:
  check_changed_files:
    name: Check changed files
    if: !contains(github.event.pull_request.labels.*.name , 'translations-check-ignore')
    runs-on: ${{ inputs.runs-on }}
    outputs:
      changed_files: ${{ steps.changed-files.outputs.locales_all_modified_files }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run changed-files with the commit of the last successful push event on current branch
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true
          files_yaml: |
            locales:
              - locales/it/*.json

      - name: List changed files
        run: echo "CHANGED_FILES=${{ steps.changed-files.outputs.locales_all_modified_files }}" >> $GITHUB_OUTPUT

  process_translations:
    name: Create Branch and tasks
    needs: [check_changed_files]
    if: ${{needs.check_changed_files.outputs.changed_files != ''}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TRANSLATIONS_BOT_APP_ID }}
          private_key: ${{ secrets.TRANSLATIONS_BOT_PRIVATE_KEY }}

      - name: lokalise
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
        uses: jimmysafe/lokalise-actions/modules/open-pr@main-v1
        with:
          lokaliseApiToken: ${{ env.LOKALISE_API_TOKEN }}
          lokaliseProjectId: ${{ env.LOKALISE_PROJECT_ID }}
          token: ${{ env.GH_TOKEN }}
