name: PR with translations
on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
      lokaliseApiToken:
        type: string
        required: true
      lokaliseProjectId:
        type: string
        required: true
      token:
        type: string
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  check_changed_files:
    name: Check changed files
    runs-on: ${{ inputs.runs-on }}
    outputs:
      changed_files: ${{ steps.changed-files.outputs.locales_all_modified_files }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run changed-files with the commit of the last successful push event on current branch
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          since_last_remote_commit: true
          files_yaml: |
            locales:
              - locales/it/*.json

      - name: List changed files
        run: echo "CHANGED_FILES=${{ steps.changed-files.outputs.locales_all_modified_files }}" >> $GITHUB_OUTPUT

  process_translations:
    name: Create Branch and tasks
    needs: [check_changed_files]
    if: ${{needs.check_changed_files.outputs.changed_files != ''}}
    runs-on: ubuntu-latest
    steps:
      - name: lokalise
        uses: ./translations-open-pr
        with:
          lokaliseApiToken: ${{ inputs.lokaliseApiToken }}
          lokaliseProjectId: ${{ inputs.lokaliseProjectId }}
          token: ${{ inputs.token }}
          # lokaliseApiToken: f65180bcef55eb0fa6bc794421b340dc6dbf0569
          # lokaliseProjectId: 175820916698d77c9ef940.96307178
          # token: ${{ secrets.MY_TOKEN}}
