name: Task Status Change
on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
      task_id:
        type: string
        required: true
      gh_data:
        type: string
        required: true

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}

# permissions:
#   id-token: write
#   contents: read
#   pull-requests: write

jobs:
  task_status_change:
    name: Task Status Change
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.TRANSLATIONS_BOT_APP_ID }}
          private_key: ${{ secrets.TRANSLATIONS_BOT_PRIVATE_KEY }}

      - name: lokalise
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
          LOKALISE_PROJECT_ID: ${{ secrets.LOKALISE_PROJECT_ID }}
        uses: jimmysafe/lokalise-actions/translations-task-status-comments@main-v1
        with:
          lokaliseApiToken: ${{ env.LOKALISE_API_TOKEN }}
          lokaliseProjectId: ${{ env.LOKALISE_PROJECT_ID }}
          token: ${{ env.GH_TOKEN }}
          gh_data: ${{ inputs.gh_data }}
          task_id: ${{ inputs.task_id }}
